### ISSUE TITLE
op-1-format-to-frame and frame-to-op-1-format are just broken, op-1-format-to-frame.new almost correct.

### ISSUE THREAD

**Issue by Yehouda** [defaultxr/bdef#2]
The function **frame-to-op-1-format**  is completely broken, and seems to a mis-interpretation o fthe code in https://github.com/padenot/libop1/blob/master/src/op1_drum_impl.cpp. The function **frame-to-op-1-format.new** is close to what the C code does. To do precisely what the C code does it needs to do:
```
 (* (floor +op-1-drumkit-end+ +op-1-bytes-in-12-sec+)
      frame +size-of-uint16-t+)
```
[assuming that **frame** is an integer]

**op-1-format-to-frame** also broken. The function **op-1-format-to-frame.new** multiply by **+size-of-uint16-t+** instead of dividing by it. To match **frame-to-op-1-format**, **op-1-format-to-frame** needs to do:  
```
(round
   (/  op-1
       (* (floor +op-1-drumkit-end+ +op-1-bytes-in-12-sec+)
          +size-of-uint16-t+)))
```

The test **op-1** will not work as is even after the fix, because op-1 value of 40 is rounded to 0. Switching the calls, so 40 is the frame number, make it work with the fixed functions.

**Comment by defaultxr** [comment]
Yes, these functions were definitely not completed and I'd been meaning to get back to them. I also have to fix the `splits-from-op-1-drumset` function as well, which I will hopefully get around to doing soon. Thank you for the corrections!
