### ISSUE TITLE
undocumented-symbols now in test-helpers, so undefined in the test

### ISSUE THREAD

**Issue by Yehouda** [defaultxr/bdef#3]
The test uses **undocumented-symbols**, which was defined in "mutility", but is now in "mutility/test-helpers", so it is undefined.

Adding  "mutility/test-helpers" to the **:depned-on** of "bdef/tests" fixes it, but it is probably better to put **undocumented-symbols** back in "mutility" itself. 

After the fix it errors with undocumented symbols: 
`(*BDEF-TEMPORARY-DIRECTORY* SPLITS-FROM-OP-1-DRUMSET BDEF-ID BDEF-KEY)`

**Comment by defaultxr** [comment]
`mutility/test-helpers` was added as a dependency for `bdef/tests` in commit b386f5cd9cea097ae62be69395fb7ebaf98817ef . If your copy of `bdef` is from the latest git commit then `undocumented-symbols` shouldn't be showing up as undefined, unless I am misunderstanding something.

As for the failure for the `undocumented-symbols` test, `*bdef-temporary-directory*` should have a docstring already ([line 11 of bdef.lisp](https://github.com/defaultxr/bdef/blob/b386f5cd9cea097ae62be69395fb7ebaf98817ef/bdef.lisp#L11)). The others aren't yet documented but I will fix them soon.

**Comment by defaultxr** [comment]
With the two commits I just pushed, `splits-from-op-1-drumset` is now implemented, and all exported symbols are properly documented. Thanks again for your help!
