### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [defaultxr/bdef#4]
Building with SBCL 2.1.10.195-bca540cd6 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 9a20de6a53cad754ed3471d08d575f50a3cd2bc7

*bdef/cl-patterns* fails to build with the following error:

```
; caught WARNING:
;   DEPRECATED-FUNCTION-WARNING: Using deprecated function BDEF::BDEF-REF -- please update your code to use a newer API.
;   The docstring for this function says:
;   Deprecated alias for `find-bdef'.
;   
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001BFC103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "bdef/cl-patterns" "cl-patterns">

```

*bdef/tests* fails to build because of a failure in  _bdef/cl-patterns_.

[Full log here](http://report.quicklisp.org/2021-11-23/failure-report/bdef.html)

**Comment by defaultxr** [comment]
Sorry about that. I've removed the reference to `bdef-ref` and replaced it with `find-bdef` which does not produce warnings. Pushed the change as commit f48153022309cdb81ee917f143b9a5a8d0f8f320 , so the latest master version of the library should now build without any warnings/errors.
